packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true

catalog:
  '@tanstack/react-query': ^5.0.0
  '@types/react': ^18.3.0
  '@types/react-dom': ^18.3.0
  eslint: ^9.0.0
  react: 18.3.1
  react-dom: 18.3.1
  sass: ^1.90.0
  typescript: ^5.9.0
  vitest: ^4.0.0
  zustand: ^5.0.0
