export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/home/index',
    'pages/courses/index',
    'pages/course-detail/index',
    'pages/cart/index',
    'pages/booking/index',
    'pages/me/index',
    'pages/my-orders/index',
    'pages/my-courses/index',
    'pages/schedule/index',
    'pages/my-bookings/index',
    'pages/notifications/index',
    'pages/teacher-portal/index',
    'pages/video-player/index',
    'pages/webview/index',
    'pages/franchise/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#f3f5f4',
    navigationBarTitleText: '选择门店',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#747c77',
    selectedColor: '#176b57',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/icons/muyi/home-deer.png',
        selectedIconPath: 'assets/icons/muyi/home-deer.png',
      },
      {
        pagePath: 'pages/courses/index',
        text: '课程',
        iconPath: 'assets/icons/muyi/course-note.png',
        selectedIconPath: 'assets/icons/muyi/course-note.png',
      },
      {
        pagePath: 'pages/franchise/index',
        text: '加盟合作',
        iconPath: 'assets/icons/muyi/franchise-deer.png',
        selectedIconPath: 'assets/icons/muyi/franchise-deer.png',
      },
      {
        pagePath: 'pages/booking/index',
        text: '预约',
        iconPath: 'assets/icons/muyi/schedule.png',
        selectedIconPath: 'assets/icons/muyi/schedule.png',
      },
      {
        pagePath: 'pages/me/index',
        text: '我的',
        iconPath: 'assets/icons/muyi/profile.png',
        selectedIconPath: 'assets/icons/muyi/profile.png',
      },
    ],
  },
})
